# Generated by Django 4.2.25 on 2026-10-02 20:54

import applications.control.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('SCTR', 'SCTR'), ('HOMOLOGACION', 'Homologación'), ('INDUCCION', 'Inducción'), ('CURSOS', 'Cursos'), ('APTITUD_MEDICA', 'Aptitud médica')], max_length=20)),
                ('curso', models.CharField(blank=True, choices=[('CALIENTE', 'Caliente'), ('ALTURA', 'Altura'), ('ESPACIO_CONFINADO', 'Espacio confinado'), ('ELECTRICO', 'Eléctrico'), ('EXCAVACION', 'Excavación'), ('IZAJE', 'Izaje')], max_length=30, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('archivo', models.FileField(upload_to=applications.control.models.certificado_upload_path)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CursoObligatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('curso', models.CharField(choices=[('CALIENTE', 'Caliente'), ('ALTURA', 'Altura'), ('ESPACIO_CONFINADO', 'Espacio confinado'), ('ELECTRICO', 'Eléctrico'), ('EXCAVACION', 'Excavación'), ('IZAJE', 'Izaje')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('homologado', models.BooleanField(db_index=True, default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=10)),
                ('dni', models.CharField(db_index=True, max_length=20)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('sctr', models.BooleanField(default=False)),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='control.empresa')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ('empresa__nombre', 'apellidos', 'nombres'),
            },
        ),
    ]
