# Generated by Django 4.2.25 on 2026-09-21 21:50

import applications.control.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=applications.control.models.certificado_upload_path)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=10)),
                ('dni', models.CharField(db_index=True, max_length=20)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('sctr', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('RECHAZADO', 'Rechazado')], default='DESAPROBADO', max_length=15)),
                ('induccion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('RECHAZADO', 'Rechazado')], default='DESAPROBADO', max_length=15)),
                ('cursos', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('RECHAZADO', 'Rechazado')], default='DESAPROBADO', max_length=15)),
                ('aptitud_medica', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('RECHAZADO', 'Rechazado')], default='DESAPROBADO', max_length=15)),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='control.empresa')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ('empresa__nombre', 'apellidos', 'nombres'),
            },
        ),
    ]
