# Generated by Django 3.2.25 on 2026-09-07

from datetime import date

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=10)),
                ('dni', models.CharField(db_index=True, max_length=20)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('INDEFINIDO', 'Indefinido'), ('TEMPORAL', 'Temporal'), ('POR_OBRA', 'Por obra o proyecto'), ('PRACTICAS', 'Prácticas'), ('OTRO', 'Otro')], max_length=20)),
                ('turno', models.CharField(blank=True, choices=[('DIA', 'Diurno'), ('NOCHE', 'Nocturno'), ('ROTATIVO', 'Rotativo')], max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores/fotos/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('HABILITADO', 'Habilitado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='control.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='control.trabajador')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trabajador',
            constraint=models.UniqueConstraint(fields=('empresa', 'dni'), name='unique_trabajador_empresa_dni'),
        ),
    ]
