# Generated by Django 3.2.25 on 2026-09-08 01:15

import applications.control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ('-created',), 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('nombre',), 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ('empresa__nombre', 'apellidos', 'nombres'), 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveConstraint(
            model_name='trabajador',
            name='unique_trabajador_empresa_dni',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_fin_contrato',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_inicio_contrato',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tipo_contrato',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='turno',
        ),
        migrations.AddField(
            model_name='certificado',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificado',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=applications.control.models.certificado_upload_path),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', django.db.models.expressions.F('fecha_emision')), _connector='OR'), name='certificado_fecha_vencimiento_no_antes_de_emision'),
        ),
        migrations.AddConstraint(
            model_name='trabajador',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'dni'), name='unique_trabajador_activo_empresa_dni'),
        ),
    ]
