# Generated by Django 4.2.25 on 2026-10-05 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='control.trabajador'),
        ),
        migrations.AddField(
            model_name='cursoobligatorio',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_obligatorios', to='control.trabajador'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='control.empresa'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='control.trabajador'),
        ),
        migrations.AddConstraint(
            model_name='trabajador',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'dni'), name='unique_trabajador_activo_empresa_dni'),
        ),
        migrations.AddConstraint(
            model_name='cursoobligatorio',
            constraint=models.UniqueConstraint(fields=('trabajador', 'curso'), name='curso_obligatorio_unico_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', True), ('trabajador__isnull', False)), fields=('trabajador', 'tipo'), name='certificado_unico_tipo_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', False), ('tipo', 'CURSOS'), ('trabajador__isnull', False)), fields=('trabajador', 'curso'), name='certificado_unico_curso_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False), ('tipo__in', ('SCTR_PENSION', 'SCTR_SALUD', 'HOMOLOGACION'))), fields=('empresa', 'tipo'), name='certificado_unico_empresa_tipo'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('curso__isnull', True), ('empresa__isnull', False), ('tipo__in', ('SCTR_PENSION', 'SCTR_SALUD', 'HOMOLOGACION')), ('trabajador__isnull', True)), models.Q(('curso__isnull', True), ('empresa__isnull', True), ('tipo__in', ('INDUCCION', 'APTITUD_MEDICA')), ('trabajador__isnull', False)), models.Q(('curso__isnull', False), ('empresa__isnull', True), ('tipo', 'CURSOS'), ('trabajador__isnull', False)), _connector='OR'), name='certificado_propietario_segun_tipo'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_vencimiento__gte', models.F('fecha_emision'))), name='certificado_fecha_vencimiento_no_antes_de_emision'),
        ),
    ]
