# Generated by Django 4.2.25 on 2026-10-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sctr_pension_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sctr_salud_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
