# Generated by Django 4.2.25 on 2026-09-23 18:39

from django.db import migrations, models
import django.db.models.deletion


def mover_sctr_a_empresa(apps, schema_editor):
    Certificado = apps.get_model('control', 'Certificado')
    vistos = set()
    for certificado in Certificado.objects.filter(tipo='SCTR').select_related('trabajador').order_by('-fecha_emision', '-pk'):
        empresa_id = certificado.trabajador.empresa_id
        if empresa_id in vistos:
            certificado.delete()
            continue
        certificado.empresa_id = empresa_id
        certificado.trabajador_id = None
        certificado.save(update_fields=['empresa', 'trabajador'])
        vistos.add(empresa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_certificados_por_tipo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_unico_tipo_trabajador',
        ),
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_unico_categoria_curso_trabajador',
        ),
        migrations.AddField(
            model_name='certificado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='control.empresa'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='control.trabajador'),
        ),
        migrations.RunPython(mover_sctr_a_empresa, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria__isnull', True), ('trabajador__isnull', False)), fields=('trabajador', 'tipo'), name='certificado_unico_tipo_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'CURSOS'), ('trabajador__isnull', False)), fields=('trabajador', 'categoria'), name='certificado_unico_categoria_curso_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False), ('tipo', 'SCTR')), fields=('empresa', 'tipo'), name='certificado_unico_sctr_empresa'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('empresa__isnull', False), ('tipo', 'SCTR'), ('trabajador__isnull', True)), models.Q(('empresa__isnull', True), ('tipo__in', ('INDUCCION', 'CURSOS', 'APTITUD_MEDICA')), ('trabajador__isnull', False)), _connector='OR'), name='certificado_propietario_segun_tipo'),
        ),
    ]
