# Generated by Django 3.2.25 on 2026-09-18 21:01

from django.db import migrations, models


def mapear_estados_legados(apps, schema_editor):
    Trabajador = apps.get_model('control', 'Trabajador')
    Trabajador.objects.filter(estado__in=('PENDIENTE', 'RECHAZADO')).update(estado='DESHABILITADO')


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='estado',
            field=models.CharField(choices=[('HABILITADO', 'Habilitado'), ('DESHABILITADO', 'Deshabilitado')], db_index=True, default='DESHABILITADO', max_length=20),
        ),
        migrations.RunPython(mapear_estados_legados, migrations.RunPython.noop),
    ]
