# Generated by Django 4.2.25 on 2026-10-08 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_trabajador_sctr_pension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe contener exactamente 11 dígitos.')]),
        ),
    ]
