# Generated by Django 3.2.25 on 2026-09-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_trabajador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='estado',
            field=models.CharField(choices=[('HABILITADO', 'Habilitado'), ('DESHABILITADO', 'Deshabilitado')], db_index=True, default='HABILITADO', max_length=20),
        ),
    ]
