# Generated by Django 4.2.25 on 2026-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_rename_habilitado_empresa_homologado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaCurso',
            new_name='Curso',
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre',), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_unico_tipo_trabajador',
        ),
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_unico_categoria_curso_trabajador',
        ),
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_propietario_segun_tipo',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='categoria',
            new_name='curso',
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', True), ('trabajador__isnull', False)), fields=('trabajador', 'tipo'), name='certificado_unico_tipo_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', False), ('tipo', 'CURSOS'), ('trabajador__isnull', False)), fields=('trabajador', 'curso'), name='certificado_unico_categoria_curso_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('curso__isnull', True), ('empresa__isnull', False), ('tipo', 'SCTR'), ('trabajador__isnull', True)), models.Q(('curso__isnull', True), ('empresa__isnull', True), ('tipo__in', ('INDUCCION', 'APTITUD_MEDICA')), ('trabajador__isnull', False)), models.Q(('curso__isnull', False), ('empresa__isnull', True), ('tipo', 'CURSOS'), ('trabajador__isnull', False)), _connector='OR'), name='certificado_propietario_segun_tipo'),
        ),
    ]
