# Generated by Django 3.2.25 on 2026-09-18 21:12

from django.db import migrations, models


def recargar_habilitado_empresas(apps, schema_editor):
    Empresa = apps.get_model('control', 'Empresa')
    Trabajador = apps.get_model('control', 'Trabajador')
    for empresa in Empresa.objects.all():
        tiene_deshabilitado = Trabajador.objects.filter(
            empresa=empresa, estado='DESHABILITADO'
        ).exists()
        empresa.habilitado = not tiene_deshabilitado
        empresa.save(update_fields=['habilitado'])


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_trabajador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(recargar_habilitado_empresas, migrations.RunPython.noop),
    ]
