# Generated by Django 4.2.25 on 2026-09-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_empresa_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='area',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='telefono',
        ),
    ]
