# Generated by Django 4.2.25 on 2026-09-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_curso_como_choices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_unico_categoria_curso_trabajador',
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', False), ('tipo', 'CURSOS'), ('trabajador__isnull', False)), fields=('trabajador', 'curso'), name='certificado_unico_curso_trabajador'),
        ),
    ]
