# Generated by Django 4.2.25 on 2026-09-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_remove_certificado_certificado_unico_categoria_curso_trabajador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='homologado',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
