# Generated by Django 4.2.25 on 2026-09-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_empresa_homologado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True),
        ),
    ]
