# Generated by Django 4.2.25 on 2026-09-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_certificado_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_unico_sctr_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='certificado',
            name='certificado_propietario_segun_tipo',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('SCTR', 'SCTR'), ('HOMOLOGACION', 'Homologación'), ('INDUCCION', 'Inducción'), ('CURSOS', 'Cursos'), ('APTITUD_MEDICA', 'Aptitud médica')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False), ('tipo__in', ('SCTR', 'HOMOLOGACION'))), fields=('empresa', 'tipo'), name='certificado_unico_empresa_tipo'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('curso__isnull', True), ('empresa__isnull', False), ('tipo__in', ('SCTR', 'HOMOLOGACION')), ('trabajador__isnull', True)), models.Q(('curso__isnull', True), ('empresa__isnull', True), ('tipo__in', ('INDUCCION', 'APTITUD_MEDICA')), ('trabajador__isnull', False)), models.Q(('curso__isnull', False), ('empresa__isnull', True), ('tipo', 'CURSOS'), ('trabajador__isnull', False)), _connector='OR'), name='certificado_propietario_segun_tipo'),
        ),
    ]
